// <auto-generated />
using System;
using AutoPrueba2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoPrueba2.Migrations
{
    [DbContext(typeof(Conexionbd))]
    [Migration("20190520125102_AutoTabla")]
    partial class AutoTabla
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutoPrueba2.Models.Auto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color");

                    b.Property<string>("Deposito");

                    b.Property<DateTime>("Fecha");

                    b.Property<string>("Marca");

                    b.Property<int>("MatriculaCaracterDos");

                    b.Property<string>("MatriculaCaracterTres");

                    b.Property<string>("MatriculaCaracterUno");

                    b.Property<string>("Modelo");

                    b.Property<string>("Tipo");

                    b.HasKey("Id");

                    b.ToTable("Autos");
                });
#pragma warning restore 612, 618
        }
    }
}
